name: Build Emacs Binary

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sudo apt-get install -y build-essential automake texinfo libjpeg-dev libncurses5-dev libtiff5-dev libgif-dev libpng-dev libxpm-dev libgtk-3-dev libgnutls28-dev libx11-dev libtiff-dev libgtk2.0-dev gnutls-dev libgtk-3-dev libxml2-dev libwebkit2gtk-4.0-dev imagemagick libmagickwand-dev libtree-sitter-dev libjansson4 libjansson-dev

    - name: Build Emacs
      run: |
        git clone https://git.savannah.gnu.org/git/emacs.git
        cd emacs
        ./autogen.sh
        ./configure
        make

    - name: Create Installation Directory
      run: |
        mkdir -p build-root
        make install prefix=build-root

    - name: Create Binary Archive
      run: |
        tar -czvf emacs-binary.tar.gz -C build-root .
      
    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v2
      with:
        name: emacs-binary
        path: emacs-binary.tar.gz



