name: Build Emacs Binary

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf texinfo libgtk-3-dev

    - name: Build Emacs
      run: |
        git clone https://github.com/emacs-mirror/emacs.git
        cd emacs
        ./autogen.sh
        ./configure
        make

    - name: Create Binary Archive
      run: |
        cd emacs
        tar -czvf emacs-binary.tar.gz src/emacs
        
    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v2
      with:
        name: emacs-binary
        path: emacs/emacs-binary.tar.gz

